server {
    listen 9000;
    server_name soflty-pinko-front-end:task2;

    root /var/www/html/softy-pinko-front-end;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
