services:
  backend:
    build: 
      context: .
      dockerfile: task4/back-end/Dockerfile
    image: softy-pinto-back-end:task4
    ports:
      - "5252:5252"


  frontend:
    build:
      context: .
      dockerfile: task4/front-end/Dockerfile
    image: softy-pinto-front-end:task4
    ports:
      - "9000:9000"
    depends_on:
      - backend
